exclude: '^(.*egg.info.*|docs/.*|.*/parameters.py$|docs/.*|.*\.py_template|.*/experimental/.*)'
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
  - repo: https://github.com/PyCQA/isort # config: .isort.cfg
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args:
          - --safe
          - --line-length=120
        language_version: python3
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: >
          (?x)^(
              license_header.txt|
              tests/resources/.*|
          )$
      - id: check-yaml
        # The first two lines of meta.yaml does not work with check-yaml
        exclude: >
          (?x)^(
              recipe/meta.yaml|
              .github/repo_meta.yaml|
          )$
      - id: debug-statements
      - id: check-ast
  - repo: https://github.com/Lucas-C/pre-commit-hooks.git
    rev: v1.1.13
    hooks:
      - id: insert-license
        name: insert-py-license
        files: >
          (?x)^(
              src/snowflake/snowml/.*\.py|
              tests/.*\.py|
          )$
        exclude: >
          (?x)^(
              src/snowflake/snowml/version.py|
              tests/resources/.*\.py|
          )$
        args:
          - --license-filepath
          - license_header.txt
  - repo: https://github.com/pycqa/flake8 # config: .flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear == 20.11.1
          - flake8-init-return == 1.0.0
  - repo: https://github.com/terrencepreilly/darglint
    rev: v1.7.0
    hooks:
      - id: darglint
        language_version: python3
        # Exclude test files.
        exclude: ^.*(_test.py)$
