# Dependencies available in the Snowflake conda channel
# are listed here.
# DO NOT add more channels. To add a dependency that's currently
# not available in the Snowflake conda channel, change conda-env-extended.yml.
#
# After updating this file, conda-env.yml should be updated. See instructions
# there.
#
# Keep all the dependencies in alphabetical order.
# Specify version explicitly for all the dependencies.

channels:
  - https://repo.anaconda.com/pkgs/snowflake
dependencies:
  - absl-py==0.15.0
  - anyio==3.5.0
  - boto3==1.24.28
  - conda-libmamba-solver==23.1.0
  - coverage==6.3.2  # not a package dependency.
  - flask-cors==3.0.10
  - flask==2.1.3
  - fsspec==2022.10.0
  - inflection==0.5.1
  - joblib==1.1.1
  - lightgbm==3.3.5
  - networkx==2.8.4
  - numpy==1.23.4
  - pandas==1.4.4
  - pytest==7.1.2
  - python==3.8.13
  - pytorch==1.12.1
  - ruamel.yaml==0.17.21
  - s3fs==2022.10.0
  - scipy==1.9.3
  - scikit-learn==1.2.2
  - snowflake-snowpark-python==1.4.0
  - sqlparse==0.4.3
  - typing-extensions==4.3.0
  - xgboost==1.7.3
  - mypy==0.981  # not a package dependency.
