# TODO(SNOW-728020): Make this file a template so that it can read ground truths
# (dependencies, version number) from a common place. We also need to define that
# common place, as currently it's a BUILD rule.
# See https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#templating-with-jinja
{% set version_match = load_file_regex(load_file='snowflake/ml/version.bzl', regex_pattern='VERSION = "(\d\.\d\.\d*)"\s.*') %}

package:
  name: snowflake-ml-python
  version: {{ version_match.group(1) }}

source:
  path: ../../

build:
  noarch: python

requirements:
  build:
    - python
    - bazel >=6.0.0
  run:
    - python
    - absl-py>=0.15,<2
    - anyio>=3.5.0,<4
    - cloudpickle
    - fsspec>=2022.11,<=2023.1
    - numpy>=1.23,<1.24
    - packaging>=23.0,<24
    - pyyaml>=6.0,<7
    - scipy>=1.9,<2
    - snowflake-connector-python
    - snowflake-snowpark-python>=1.4.0,<=2
    - sqlparse>=0.4,<1
    - typing-extensions>=4.1.0,<5

    # conda-libmamba-solver is conda-specific requirement, and should not appear in wheel's dependency.
    - conda-libmamba-solver>=23.1.0,<24

    # TODO(snandamuri): Versions of these packages must be exactly same between user's workspace and
    # snowpark sandbox. Generic definitions like scikit-learn>=1.1.0,<2 wont work because snowflake conda channel
    # only has a few allowlisted versions of scikit-learn available, so we must force users to use scikit-learn
    # versions that are available in the snowflake conda channel. Since there is no way to specify allow list of
    # versions in the requirements file, we are pinning the versions here.
    - scikit-learn>=1.2.1,<2
    - xgboost==1.7.3
about:
  home: https://github.com/snowflakedb/snowflake-ml-python
  license: Apache-2.0
  license_family: Apache
  license_file: ../../LICENSE.txt
  summary: Snowflake ML Library
  description: |
    Snowflake ML client Library is used for interacting with Snowflake to build machine learning solutions.
    Functionalities include feature engineering, modeling, model management, deployment, etc
  dev_url: https://github.com/snowflakedb/snowflake-ml-python
  doc_url: https://github.com/snowflakedb/snowflake-ml-python/blob/main/README.md
